HouseRoute135_MapScripts::
	.byte 0


aquaTrainer_HouseRoute135::
# 6 "data/maps/HouseRoute135/scripts.pory"
	lockall
# 7 "data/maps/HouseRoute135/scripts.pory"
	faceplayer
# 8 "data/maps/HouseRoute135/scripts.pory"
	msgbox aquaTrainer
# 9 "data/maps/HouseRoute135/scripts.pory"
	waitmessage
# 10 "data/maps/HouseRoute135/scripts.pory"
	releaseall
	end


magmaTrainer_HouseRoute135::
# 15 "data/maps/HouseRoute135/scripts.pory"
	lockall
# 16 "data/maps/HouseRoute135/scripts.pory"
	faceplayer
# 17 "data/maps/HouseRoute135/scripts.pory"
	msgbox magmaTrainer
# 18 "data/maps/HouseRoute135/scripts.pory"
	waitmessage
# 19 "data/maps/HouseRoute135/scripts.pory"
	releaseall
	end


magmaTrainer::
# 23 "data/maps/HouseRoute135/scripts.pory"
	.string "I had a runin with SAM,\n he convinced me that Maxie was\p going to far. I'm \n officially retired.$"

aquaTrainer::
# 27 "data/maps/HouseRoute135/scripts.pory"
	.string "What people do for love,\n Unrequited unfortunately.\p Archie also scares me..$"
